version: '3'
services:
  frontend:
    image: nginx:latest
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/
      - cache:/data/nginx/cache
    ports:
      - "80:80"
    networks:
      - backend

  versatiles:
    build: docker/versatiles/
    volumes:
      - ./data/tiles/:/data/tiles/
      - ./data/static/:/data/static/
    networks:
      - backend

networks:
  backend:

volumes:
  cache:
