version: '3'
services:
  frontend:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/
      - cache:/data/nginx/cache
    ports:
      - "80:80"
    networks:
      - backend

  versatiles:
    image: versatiles/versatiles:latest-scratch
    restart: always
    volumes:
      - ./data/tiles/:/data/tiles/
      - ./data/static/:/data/static/
    networks:
      - backend
    command: '/usr/local/cargo/bin/versatiles serve -i 0.0.0.0 -p 8080 -s /data/static /data/tiles/osm.versatiles'

  maputnik:
    image: maputnik/editor
    restart: always
    ports:
      - "8888:8888"
    networks:
      - backend

networks:
  backend:

volumes:
  cache:
